import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import AppbarMain from '../components/AppbarMain'
import { Card, CardContent, Skeleton, Tab, Typography } from '@mui/material'
import { Box } from '@mui/system'
import TabMain from '../components/core/TabMain'
import CardList from '../components/module/surah/CardList'
import BookmarkBorderSharpIcon from '@mui/icons-material/BookmarkBorderSharp';
import { useEffect, useState } from 'react'
import { useQuery } from 'react-query';





export default function MainPage() {

  const [resData, setResData] = useState([]);



  const fetchData = async () => {
      const response = await fetch('/api/allSurah');
      const data = await response.json();
      // setResData(data.data);
      return data.data
  };

  const { data, isLoading, error } = useQuery('exampleQueryKey', fetchData);

  // useEffect(() => {

  //   const fetchData = async () => {
  //     try {
  //       const response = await fetch('/api/allSurah');
  //       const data = await response.json();
  //       console.log("Data ", data.data);
  //       setResData(data.data);
  //     } catch (error) {
  //       console.error('Error fetching data:', error);
  //     }
  //   };

  //   fetchData();

  // }, []);

  if(isLoading) {
    return (  
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Skeleton variant="rectangular" width={100} height={100} />
      </main>
    </>
    )
  }

  if(error) {
    return <p> error ... </p>
  }

  if(data) {
     setResData(data)
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
     <AppbarMain />
     <Box sx={{zIndex:"1000"}}> 
     <Card className="cardImg">
     <Box className="imgHome"> 
      <Image src="/img/alquran-transparent.png" alt="imgHome" width={120} height={120}/> 
      </Box>
       <CardContent>
        <Box sx={{display: 'flex', flexDirection: 'row', alignItems: 'center', gap: '2px'}}> 
          <BookmarkBorderSharpIcon />
          <Typography sx={{fontSize: '12px'}}>  Last Read </Typography>
        </Box>
       
         <Box sx={{marginTop: '40px'}}>
         <Typography sx={{fontSize: '18px',fontWeight: '700'}}> Al-Faatiha </Typography>
         <Typography sx={{fontSize: '13px', fontWeight: '300', marginTop: '10px'}}> Ayah No.3 </Typography>
         </Box>
       </CardContent>
     </Card>
    <TabMain />
    <Box sx={{marginTop: '20px'}}> 
    <CardList resData={resData}/>
    </Box>
  
     </Box>

     
      </main>
    </>
  )
}
